version: "3.9"

networks:
  elasticsearch:
    external: true

services:
  elasticsearch:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elastic-data:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: kibana
    ports:
      - 5601:5601
    volumes:
      - kibanadata:/usr/share/kibana/data
    environment: 
      SERVERNAME: kibana
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200

volumes:
  elastic-data:
    driver: local
  kibanadata:
    driver: local